### ISSUE TITLE
버그

### ISSUE THREAD

**Issue by Kieaer** [Aboa123/VT-VrchatTogether-#7]
블락 관리 -> 블락한 아무 유저 선택 -> 블락 해제할려고 하면 금지 표시가 회색이며 블락 할꺼냐는 팝업이 뜸

**Comment by Kieaer** [comment]
블락 목록을 갱신하는 버튼을 누르면 앱 크래시남.
stacktrace 를 전송했으므로 구글 앱 관리 사이트에서 확인가능

**Comment by Aboa123** [comment]
제보 감사합니다. 빠른시일내에 수정하도록하겠습니다.
